export default {
  DATA_REQUEST: "DATA/REQUEST",
  DATA_SUCCESS: "DATA/SUCCESS",
  DATA_ERROR: "DATA/ERROR",
  POST_REQUEST: "POST/REQUEST",
  POST_SUCCESS: "POST/SUCCESS",
  POST_ERROR: "POST/ERROR",
  ADD_DREAM: "DREAM/ADD",
};
